# conda env export --from-history
name: smmo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask
  - flask-jwt-extended
  - flask-restful
  - flask-sqlalchemy
  - flask-migrate
  - marshmallow
  - marshmallow-oneofschema
  - psycopg2
  - requests
  - gunicorn
