"""Initial migration.

Revision ID: 03cef6a3b752
Revises: 
Create Date: 2021-08-11 09:49:36.220749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03cef6a3b752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_playercache_uid'), 'playercache', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playercache_uid'), table_name='playercache')
    # ### end Alembic commands ###
