"""February update

Revision ID: 31798b393dd5
Revises: aba2fbbcc8fb
Create Date: 2022-02-09 00:29:34.029689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "31798b393dd5"
down_revision = "aba2fbbcc8fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("quests_performed", sa.Integer(), nullable=False, server_default="-1"))

    # clear server_defaults
    for field in ["quests_performed"]:
        op.alter_column("player", field, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player", "quests_performed")
    # ### end Alembic commands ###
