"""Added index to Player uid

Revision ID: a6aa5ccc7f76
Revises: 03cef6a3b752
Create Date: 2021-08-11 13:38:56.661226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6aa5ccc7f76"
down_revision = "03cef6a3b752"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_player_uid"), "player", ["uid"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_uid"), table_name="player")
    # ### end Alembic commands ###
