"""December 13 update

Revision ID: aba2fbbcc8fb
Revises: e2b55c6f21f9
Create Date: 2021-12-13 15:46:46.289381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aba2fbbcc8fb"
down_revision = "e2b55c6f21f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player",
        sa.Column("location_id", sa.Integer(), nullable=False, server_default="-1"),
    )
    op.add_column(
        "player",
        sa.Column("location_name", sa.String(), nullable=False, server_default=""),
    )

    # clear server_defaults
    for field in ["location_id", "location_name"]:
        op.alter_column("player", field, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player", "location_name")
    op.drop_column("player", "location_id")
    # ### end Alembic commands ###
