"""Added new columns

Revision ID: e2b55c6f21f9
Revises: a6aa5ccc7f76
Create Date: 2021-11-10 17:45:46.702308

"""
from datetime import datetime, timezone
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2b55c6f21f9"
down_revision = "a6aa5ccc7f76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player",
        sa.Column(
            "creation_date",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=str(datetime.min.replace(tzinfo=timezone.utc)),
        ),
    )
    op.add_column(
        "player",
        sa.Column("reputation", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player",
        sa.Column("tasks_completed", sa.Integer(), nullable=False, server_default="-1"),
    )
    op.add_column(
        "player",
        sa.Column(
            "bounties_completed", sa.Integer(), nullable=False, server_default="-1"
        ),
    )
    op.add_column(
        "player",
        sa.Column("chests_opened", sa.Integer(), nullable=False, server_default="-1"),
    )
    op.add_column(
        "player",
        sa.Column(
            "dailies_unlocked", sa.Integer(), nullable=False, server_default="-1"
        ),
    )
    op.add_column(
        "player", sa.Column("avatar", sa.String(), nullable=False, server_default="")
    )
    op.add_column(
        "player",
        sa.Column("market_trades", sa.Integer(), nullable=False, server_default="-1"),
    )
    op.add_column(
        "player",
        sa.Column(
            "last_activity",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=str(datetime.min.replace(tzinfo=timezone.utc)),
        ),
    )
    op.add_column(
        "player",
        sa.Column("boss_kills", sa.Integer(), nullable=False, server_default="-1"),
    )
    # clear server_defaults
    for field in [
        "creation_date",
        "reputation",
        "tasks_completed",
        "bounties_completed",
        "chests_opened",
        "dailies_unlocked",
        "avatar",
        "market_trades",
        "last_activity",
        "boss_kills",
    ]:
        op.alter_column("player", field, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player", "boss_kills")
    op.drop_column("player", "last_activity")
    op.drop_column("player", "market_trades")
    op.drop_column("player", "avatar")
    op.drop_column("player", "dailies_unlocked")
    op.drop_column("player", "chests_opened")
    op.drop_column("player", "bounties_completed")
    op.drop_column("player", "tasks_completed")
    op.drop_column("player", "reputation")
    op.drop_column("player", "creation_date")
    # ### end Alembic commands ###
